language: r
sudo: FALSE
compiler: clang

r:
  - release
  - devel

cache:
  apt: true
  packages: true
  ccache: true

addons:
  apt:
    packages:
      - libudunits2-dev
      - libv8-dev
      - libgsl-dev
      - libgdal-dev
      - libproj-dev

r_packages: ## should be r_binary_packages
 - ez
 - shiny
 - rstanarm
 - brms
 
